//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace furn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_invoice
    {
        public int pkID { get; set; }
        public int fkUserID { get; set; }
        public int fkPID { get; set; }
        public bool status { get; set; }
        public string transid { get; set; }
        public string tracking_id { get; set; }
        public int FactorNumber { get; set; }
    
        public virtual tbl_Product tbl_Product { get; set; }
        public virtual tbl_users tbl_users { get; set; }
    }
}
